[project]
name = "projet-3"
version = "0.1.0"
description = "Seattle energy ML"
authors = [
    {name = "Cheick"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sklearn (>=0.0.post12,<0.1)",
    "pandas (>=2.3.1,<3.0.0)",
    "numpy (>=2.3.2,<3.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "matplotlib (>=3.10.5,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
